# ~/.config/starship.toml

# Use custom format
format = """
[🚀](bold green) $directory$git_branch$python
"""

command_timeout = 1000

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the newline at the start of the prompt
add_newline = false

[directory]
truncation_length = 5
style = "bold cyan"

[git_branch]
style = "bold purple"

[python]
pyenv_version_name = true
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

